FROM ubuntu:latest

# Mise à jour et installation des dépendances système
RUN apt-get update && apt-get install --yes \
    curl \
    openjdk-8-jre-headless \
    unzip libfindbin-libs-perl default-jre \
    python3 \
    python3-dev \
    python3-venv \
    python3-pip \
    procps \
    && curl -s https://get.nextflow.io | bash \
    && mv nextflow /usr/local/bin/

# Empêche Python de générer des fichiers .pyc
ENV PYTHONDONTWRITEBYTECODE=1

# Empêche Python de bufferiser les sorties
ENV PYTHONUNBUFFERED=1

# Créer un environnement virtuel Python et installer les packages requis
RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install pandas numpy tqdm openpyxl

# Ajouter le venv au PATH
ENV PATH="/opt/venv/bin:$PATH"

# Dossier de travail
WORKDIR /app

# Copier les fichiers de l'application
COPY . /app

# Commande par défaut (modifiable)
CMD ["python"]
